fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    augeas_core: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
  symlinks:
    smartd: "#{source_dir}"
